trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'matatika'

- task: Maven@3
  inputs:
    mavenPomFile: 'langchain4j-elasticsearch/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: 'package -Dmaven.javadoc.skip'
