trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: matatika

- task: Maven@3
  displayName: 'Package'
  inputs:
    mavenPomFile: 'langchain4j-elasticsearch/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: 'package -Dmaven.javadoc.skip'

- task: Maven@3
  displayName: 'Deploy'
  inputs:
    mavenPomFile: 'langchain4j-elasticsearch/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: true
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: '-e -Dmaven.javadoc.skip -Drevision=0.23.0-SNAPSHOT jar:jar org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltDeploymentRepository=matatika::https://pkgs.dev.azure.com/matatika/_packaging/matatika/maven/v1'

