trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'matatika'

- task: Maven@3
  inputs:
    mavenPomFile: 'langchain4j-elastic/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: true
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'deploy'
